# Generated by Django 4.2 on 2025-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('USER', 'USER'), ('CUSTOMER', 'CUSTOMER'), ('CHARITY_MANAGER', 'CHARITY_MANAGER')], default='USER', max_length=50),
        ),
    ]
