# Generated by Django 4.2 on 2025-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WALLET', 'Wallet')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
