# Generated by Django 4.2 on 2025-10-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_campaignevent'),
        ('on_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainCampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_on_chain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_chain_data', to='charity.campaignevent')),
            ],
            options={
                'verbose_name': 'On-Chain Campaign Event',
                'verbose_name_plural': 'On-Chain Campaign Events',
            },
        ),
    ]
