# Generated by Django 4.2 on 2025-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_campaignevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='contract_address',
        ),
        migrations.AddField(
            model_name='campaign',
            name='on_chain_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='on_chain_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
