# Generated by Django 4.2 on 2025-10-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_remove_campaign_contract_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='deployment_hash',
            new_name='transaction_hash',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='deployment_hash',
            new_name='transaction_hash',
        ),
    ]
