# Generated by Django 4.2 on 2025-10-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0006_rename_deployment_hash_campaign_transaction_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
